### ISSUE TITLE
Issue in "seldon-container-engine" with MLFLOW_SERVER

### ISSUE THREAD

**Issue by Nithinbs18** [adriangonz/mlflow-talk#1]
Hello Adrian,

Firstly thank you very much for the amazing talk on youtube and the source code for it.
I have an issue while running this content on my PC. I am using docker for desktop with K8 installed I exactly followed instructions in your jupyter notebook to set up seldon-core, seldon-analytics, and ambassador. I have my model in a remote Minio bucket. The initContainer classifier-model-initializer and the classifier executed successfully. I have a new issue in the "seldon-container-engine"

```
{"level":"info","ts":1591611950.8325408,"logger":"SeldonRestApi","msg":"Listening","Address":"0.0.0.0:8000"}
{"level":"error","ts":1591611965.4901059,"logger":"SeldonRestApi","msg":"Ready check failed","error":"dial tcp 127.0.0.1:9000: connect: connection refused","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).checkReady\n\t/workspace/api/rest/server.go:198\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1\n\t/workspace/api/rest/server.go:176\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/seldonio/seldoncore/executor/api/rest.puidHeader.func1\n\t/workspace/api/rest/server.go:191\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}
```
Could you please help me out with this or suggest to me where I am going wrong!
Thank you very much.

Regards,
Nithin

**Comment by adriangonz** [comment]
Hey @Nithinbs18, I'm glad that you enjoyed the talk! 

We can continue the discussion on the other thread in the `seldon-core` repo: https://github.com/SeldonIO/seldon-core/issues/1922
